### ISSUE TITLE
APIException is being raised without first being imported

### ISSUE THREAD

**Issue by pgautier404** [cohesity/management-sdk-python#13]
## 🐛 Bug Report

In multiple places in the SDK code, an exception of class `APIException` is being raised without the exception class first being imported. This is causing a `NameError` exception to be thrown, which is obscuring reporting of the actual root cause of the exceptional condition.

In addition to that, there are numerous places in the SDK code that try to access a `message` property from an exception. That property was deprecated in Python 2.6 and removed from Python 3, and attempting to access it is causing `AttributeError` exceptions. See [PEP 352](https://www.python.org/dev/peps/pep-0352/) for details.

## To Reproduce

(Write your steps here:)

1. Instantiate `CohesityClient` to connect to a cluster, intentionally using an incorrect password.
2. Try to authorize the resulting client object (`client.auth.authorize()`)
3. Observe a series of exceptions that finally result in `NameError: name 'APIException' is not defined`

## Expected behavior

I expected the inner `APIException` to be raised, allowing me to catch and handle it.

## Actual Behavior

An additional `NameError` exception is encountered attempting to handle the root cause exception, and that follow-on exception is the one being raised in my code.

**Comment by ashish-cohesity** [comment]
Ack @pgautier404  , will look at this.
