### ISSUE TITLE
Make multi-cluster application is impossible

### ISSUE THREAD

**Issue by alex-ikse** [cohesity/management-sdk-python#21]
## 🐛 Bug Report

I try to write an application that need to connect to 2 cohesity cluster at the same time (thread). But the configuration is stored as class variable so it is "application wide".
Impossible to have 2 CohesityClient instance on 2 different clusters. 

## To Reproduce

```python
from cohesity_management_sdk.cohesity_client import CohesityClient

c1 = CohesityClient(
    cluster_vip="cluster-source.example.net", username="backup_reports", password="...",
)


c2 = CohesityClient(
    cluster_vip="cluster-dest.example.net", username="backup_reports", password="...",
)

print(c1.config().cluster_vip)
print(c2.config().cluster_vip)
```
## Expected behavior

```
cluster-source.example.net
cluster-dest.example.net
```

## Actual Behavior

```
cluster-dest.example.net
cluster-dest.example.net
```

**Comment by ashish-cohesity** [comment]
Right on @alex-ikse  , We have identified the fix and provided a patch in the SDK for v1.1.4, this is compatibile with cluster version 6.3.1 . 

Do try it out and let us know : 
`pip install cohesity-management-sdk==1.1.4`

**Comment by ashish-cohesity** [comment]
We are planning to have a generic fix in the later versions soon.

**Comment by ashish-cohesity** [comment]
This is completed with latest release. Thanks @alex-ikse  for the patience.
