### ISSUE TITLE
API tokens for SSO users

### ISSUE THREAD

**Issue by ttripp** [cohesity/management-sdk-python#28]
## ❓ Questions and Requests

Based on the API documentation, the only way to retrieve an access token is by username and password. We've will be enabling Cohesity with an SSO IDP (e.g. SAML or OIDC). It does not look like SSO based access is supported via API and CLI:

https://helios.cohesity.com/docs/restApiDocs/browse/

`/public/accessTokens`

Is there a way to get an access token for SSO users?

**Comment by ashish-cohesity** [comment]
Hi @ttripp , Thanks for the question. 

That is a SSO by design. Once we get the SAML response back from SSO , we identify the user distinctly internally and not with an accessToken.

**Comment by ttripp** [comment]
Hi @ashish-cohesity,

I understand how that would work for UI access, but I don't understand how that works with API access.  Based on the following:

- https://developer.cohesity.com/docs/getting-started-65

The first step is to call 

```POST /public/accessTokens```

And provide:

```
{
  "password": "password",
  "username": "user",
  "domain": "LOCAL"
}
```
You then get an access token that you put into the header:

```
'Authorization: Bearer {TOKEN}'
```

Is there a mechanism to Login via SSO (e.g. SAML) and get an access token for subsequent API requests?

**Comment by chandrashekar-cohesity** [comment]
Hi @ttripp,

I am assuming that you need this token for some sort of automation. If yes, Starting from Cohesity Cluster version 6.5.1, we support generating apiKeys that can be used for such automation.

If you are using Cohesity Helios, it already supports apiKey for automation.

**Comment by ttripp** [comment]
@chandrashekar-cohesity 

All I see is documentation on using a local user to get API access keys.  I've configured our cohesity for SAML and now I need our SAML based users to be able to get an API access token.  Is there a way for these users to get an API access tokens once they are signed in via SAML?  

![image](https://user-images.githubusercontent.com/6423006/97903058-b55be680-1cfb-11eb-85df-e6a23240f3b9.png)

Where can I find docs on using the CLI for SSO users? 

Thanks,
Travis

**Comment by ttripp** [comment]
I realize this is closed, but I want to note that when I try to use an SSO domain from the CLI that it doesn't work:

```
$ ./iris_cli -server <my-server> -domain <my-sso-domain)
Error: Authentication failed: Domain '<redacted>' does not exist
```

**Comment by chandrashekar-cohesity** [comment]
I am checking this and I will get back to you

**Comment by chandrashekar-cohesity** [comment]
Hi. @ttripp, We recently updated the API documentation with 6.5.1. It covers [generating an apiKey](https://developer.cohesity.com/apidocs-651.html#/rest/api-endpoints/principals/create-user-api-key) for making API calls.

You cannot do an SSO login using iris_cli because it usually involves an 2-factor authentication and it is not possible using CLI. Also having a way to do a SSO login using CLI would defeat the purpose of SSO to provide more security.

However if you want, you can use browser developer tools and get the cookie value and use that cookie to make further API call. I would encourage using apiKey.

**Comment by ttripp** [comment]
@chandrashekar-cohesity Thanks for the info on generating an API key.

We use SSO today with a CLI in a variety of places.  Azure CLI, Gcloud CLI, etc.  It works if you use OIDC.  Browser simply opens a redirects back to a port running locally.

https://medium.com/@balaajanthan/openid-flow-from-a-cli-ac45de876ead
