### ISSUE TITLE
Anfield does not handle Blackout periods

### ISSUE THREAD

**Issue by w0rd3r** [cohesity/management-sdk-python#36]
## ❓ Questions and Requests
Hello, we do have an issue regarding Anfield.

When we export, then import, the Python module to import does not handle blackout periods of protection jobs.

You can see output below:

root@sqvmsauvelst01:/home/management-sdk-python-master/samples/project-anfield# python3 import_cluster_config10-59
INFO:import_app:Importing cluster config

INFO:import_app:Importing gflags

INFO:import_app:Importing Storage domains

INFO:import_app:Importing remote clusters

INFO:import_app:Importing Views

INFO:import_app:Importing Targets

INFO:import_app:Importing Sources

INFO:import_app:Importing Policies

INFO:import_app:Importing Jobs

INFO:import_app:Imported resources summary.
INFO:import_app:Gflag services:
kIris, kBridge, kNewScribe

INFO:import_app:Storage Domains:
DefaultStorageDomain

INFO:import_app:Protection Views:
nfsview, TestBob2

INFO:import_app:Protection Sources:
sourceFQDN

INFO:import_app:Protection Policies:
Bronze, Default Policy, Gold, replication_A, policy_poc, Silver, policy_tag

INFO:import_app:Protection Jobs:
from13to14protection_poc, from13to14protection_tag, from13to14protection_view

ERROR:import_app:Please find the error list/corrective actions:
ERROR:import_app:         1: Error creating Policy: Qualif, **failed with error: 'BlackoutPeriod' object has no Id**'

ERROR:import_app:         2: Protection policy not available for job from13to14QSIA

If it's an urgent request, Please contact us instead.
- [Cohesity API Team](cohesity-api-sdks@cohesity.com)

**Comment by pyashish** [comment]
Thanks for opening issue @w0rd3r . 
Can you let us know the SDK version and cluster version you are trying this on ?

**Comment by w0rd3r** [comment]
Thanks

6.5.1d
And sdk dowloaded from latest release today

Bob

Le mer. 13 janv. 2021 à 18:53, Ashish Bhat <notifications@github.com> a
écrit :

**Comment by naveena-maplelabs** [comment]
@w0rd3r , Issue is fixed and patch release is made. Please install the latest sdk to avail the same. https://pypi.org/project/cohesity-management-sdk/1.5.2/
