### ISSUE TITLE
[BUG] Wrong value in server_type_enum.py

### ISSUE THREAD

**Issue by aankri** [cohesity/management-sdk-python#60]
## 🐛 Bug Report

In file : cohesity_management_sdk\models\server_type_enum.py , enum value are wrong.

## To Reproduce

1.
```
body = KmsConfiguration()
body.server_type = ServerTypeEnum.KAWSKMS
kms_configuration_controller.create_kms_config(body)
```
2. Error 400

## Expected behavior

Can created an AWS KMS.
Resolved by changing line 22 to 
`KAWSKMS = 'kAwsKMS'`

Maybe other value are false too.

## Actual Behavior

`Response status code: 400, Response message: Error while parsing request body: unrecognized enum ClusterConfigProto_KMSConfig_Type value "kAwsKms"
`

**Comment by naveena-maplelabs** [comment]
@aankri  What is the cohesity cluster version you're using?

**Comment by aankri** [comment]
Hello @naveena-maplelabs 
Current Version: 6.6.0d_u4_release-20220608_0753663c

**Comment by naveena-maplelabs** [comment]
The SDK is generated based on 6.6.0x version API yaml file which contains aws type provided as follows, SDKs will support  most of the features within a major release, still some of minor changes like this are missed.
```
serverType:
        description: |-
          Specifies the type of key mangement system.
          'kInternalKms' indicates an internal KMS object.
          'kAwsKms' indicates an Aws KMS object.
          'kCryptsoftKms' indicates a Cryptsoft KMS object.
        type: string
        enum:
        - kInternalKms
        - kAwsKms
        - kCryptsoftKms
```

**Comment by aankri** [comment]
I'm not sure to understrand what you trying to say. The SDK is not up to date ? You are not updating the SDK when the API change ?

**Comment by naveena-maplelabs** [comment]
We don't generate SDK for minor releases, we update for only major releases and patch releases for bugs reported. In many of the 6.6.x versions the enum type is provided as kAwsKms. It seems to be modified in later releases after which we have upgraded the sdk to latest versions.

**Comment by BCohesian** [comment]
According to your last answer about major releases supported, does it last 6.8.1 is clearly supported or SDK will be updated? thanks

**Comment by naveena-maplelabs** [comment]
Python SDK for Cluster version 6.8.1 is currently not available, we are planning for it.

**Comment by BCohesian** [comment]
> Python SDK for Cluster version 6.8.1 is currently not available, we are planning for it.

Thanks for your quick answer, but according to the official Cohesity Global Support & Services Handbook (see diagram page 18: https://www.cohesity.com/agreements-docs/cohesity-global-support-and-services-handbook-en.pdf), the 6.8.1 is a minor release. So do you consider a minor release a maintenance release, a hotfix release, or both.
