### ISSUE TITLE
[BUG / DOCUMENTATION INCOMPLETE] 'key_name' doesn't exist in KmsConfiguration class

### ISSUE THREAD

**Issue by aankri** [cohesity/management-sdk-python#61]
## 🐛 Bug Report

Can't create a KMS, I have this error : Response status code: 400, Response message: KMS Key Name is empty.
By looking the attribute of a KMS created using GUI with `kms_configuration_controller.get_kms_config() ` , i see an attribute named 'key_name'. This attribute is not in KmsConfiguration class, and it look like it is mandatory.

## To Reproduce

1. Trying to create an AWS kms
2. Run it
3. `Response status code: 400, Response message: KMS Key Name is empty.`

## Expected behavior

Can created aws KMS

## Actual Behavior

`Response status code: 400, Response message: KMS Key Name is empty.`

**Comment by aankri** [comment]
Key Name is also not present on the doc : https://developer.cohesity.com/apidocs-64.html#/python/models/structures/kms-configuration

**Comment by naveena-maplelabs** [comment]
@aankri The documentation you're referring to is the older one, you can check the latest one available [here](https://developer.cohesity.com/apidocs/660x/#/http/api-endpoints/kms-configuration/create-kms-config)

**Comment by naveena-maplelabs** [comment]
@aankri We generate individual SDK versions for different cluster versions, you can the refer the SDK(1.6.0) for 6.6.x release.

**Comment by aankri** [comment]
@naveena-maplelabs  can you please give the link ?
There is no link for python 6.6 on this page too https://developer.cohesity.com/versions.html

**Comment by naveena-maplelabs** [comment]
For creating the kms_config, use **[kms_create_request_parameters](https://github.com/cohesity/management-sdk-python/blob/master/cohesity_management_sdk/models/kms_create_request_parameters.py)** module.
Controller [reference](https://github.com/cohesity/management-sdk-python/blob/72478c452044b24c68287b174cd56f6a5bfb3e32/cohesity_management_sdk/controllers/kms_configuration_controller.py#L150)

**Comment by aankri** [comment]
Thanks, but I still need the link for the SDK doc up to date, do you have it ?

**Comment by naveena-maplelabs** [comment]
@aankri You can refer to the documentation available [here](https://cohesity.github.io/management-sdk-python/index.html).
Page contains both V1 and V2 documentation, You can ignore the V2 API documentation which is a beta release.

**Comment by naveena-maplelabs** [comment]
Closing the ticket, please feel free to reopen if you have any queries.

**Comment by aankri** [comment]
Thanks, i'm going to look at this neext week
