### ISSUE TITLE
Export/Import policy with datalock

### ISSUE THREAD

**Issue by BCohesian** [cohesity/management-sdk-python#65]
## ❓ Questions and Requests

Try to export/import conf from one platform to another: there is an issue when importing policies with folowing message : `ERROR:import_app: Error Creating Policy: [PolicyName], failed with error: Response status code: 500, Response message: Local retention has worm policy, extented retention should also have worm policy.`

Does it mean WORM policy is not supported? Do you already tested that?

Thanks

**Comment by naveena-maplelabs** [comment]
@BCohesian I will look into this and get back to you.

**Comment by naveena-maplelabs** [comment]
@BCohesian WORM policy needs some code changes. Its currently not supported.

**Comment by BCohesian** [comment]
Thanks for your answer.

Do you have a plan to apply the changes? If you can share with me this plan
or date that will help me to update my project calendar.
The first goal is to deploy 2 Clusters for a prospect named MONACO CLOUD.
He's a new sovereign MSP localized in MONACO territory. All workloads will
be 100% VMware. vCloud Director and Cohesity vCD extension are embedded to
manage organizations backup.
Export/Import configuration script will be a part of security and automatic
refresh between clusters.


Regards,

Bertrand Le Quellec
Senior System Engineer, France.
+33 614 075 668
***@***.***



*cohesity.com/fr/ <https://www.cohesity.com/fr/>*


2 minutes pour comprendre Cohesity en vidéo :

https://www.youtube.com/watch?v=sE7lgGIwfeo

**Comment by naveena-maplelabs** [comment]
@BCohesian Currently we are not supporting Vcloud director migration.
Regarding the plan, our sprints are loaded for the currently. I'll check with the team and update you.
