### ISSUE TITLE
When updating a protection job, it just says "'{"errorCode":"KInternalError","message":"Request failed with error code: KInvalidRequest"}" . No other explanation

### ISSUE THREAD

**Issue by anusajith** [cohesity/management-sdk-python#81]
## 🐛 Bug Report

Hey Team, 
I am trying to update a protection job (Cohesity view type) by adding one newly created view to it.

## To Reproduce
These are the snippets  I am using:
1. Getting the protection job by name :

def get_protection_job_by_name(self, group_name: str):
        protection_job_list = self._client.protection_jobs.get_protection_jobs()
        for job in protection_job_list:
            if job.name == group_name:
                return job
        return None
existing_job =get_protection_job_by_name("cohesity views")

2.  getting view id of the new view created eg: 11111111
3. As a work around: When fetching a Protection Job , source Ids are not same as the View Ids. So When we are trying to update a protection job with 100+ views in it, we have to explicitly convert those source ids to respective View Ids and then run the update method.(view_source_ids)

5. new_source_ids= view_source_ids.append(11111111)

 job_body = ProtectionJobRequestBody(
                name=job_info["job_name"],
                source_ids=new_source_ids,
                policy_id=existing_job.policy_id,
                view_box_id=existing_job.view_box_id,
                environment="kView",
                timezone="Australia/Sydney",
            )
            job_body.id = existing_job.id
6. cohesity_client.protection_jobs.update_protection_job(job_body, existing_job.id)

## Expected behavior

update protection job should be successful.

## Actual Behavior
It is failing with following error:
'{"errorCode":"KInternalError","message":"Request failed with error code: KInvalidRequest"}\n'

No other explanations . It is working through UI without any issues.
How can I validate the ProtectionJobRequestBody I am sending is proper? or where am I going wrong?

Regards,
Anu

**Comment by naveena-maplelabs** [comment]
@anusajith Will check and let you know

**Comment by naveena-maplelabs** [comment]
@anusajith What is the cluster version and SDK version you're using?

**Comment by anusajith** [comment]
sdk version - 1.10.1
cluster version - 6.8.1_u5_release-20230907_89061e30

**Comment by anusajith** [comment]
here I am trying to add more than 100 views to the cohesity view type protection job. Is there a limit to that number through api?

**Comment by naveena-maplelabs** [comment]
@anusajith  I m using a 7.0 cluster. I was able to create and update job using viewId(not source id) with SDK. The issue doesn't seem to be with SDK, can you please try with different cluster version?

**Comment by anusajith** [comment]
![image](https://github.com/cohesity/management-sdk-python/assets/88121157/9721314f-269c-49b3-85f7-461d5f56d009)

Did you try updating a Protection job with more than 100 + views in it as shown.?
For me, also, the update will work till the number reaches 100. After 100, it is failing with the error mentioned.
Can you please confirm on this?

**Comment by anusajith** [comment]
@naveena-maplelabs , can you please provide an update, as this is stopping our automation for cohesity provision.

**Comment by naveena-maplelabs** [comment]
@anusajith I was able to reproduce the issue when the total number of views greater than 100. Have reported to the concerned team, Can you try View_job creation using V2 APIs?

**Comment by anusajith** [comment]
@naveena-maplelabs Thank you for that. 
Will you be able to confirm the ETA on this fix? 
And can you please share some examples for creating view , protection job and updating these using V2 client.

**Comment by naveena-maplelabs** [comment]
@anusajith 

You can install the V2 SDK using following command.
**pip install cohesity-sdk**

Links:
https://pypi.org/project/cohesity-sdk/
https://github.com/cohesity/cohesity_sdk/

Sample Code:

```
from cohesity_sdk.cluster.cluster_client import ClusterClient
from cohesity_sdk.cluster.model.create_or_update_protection_group_request import (
    CreateOrUpdateProtectionGroupRequest,
)
from cohesity_sdk.cluster.model.view_protection_group_params import (
    ViewProtectionGroupParams,
)
from cohesity_sdk.cluster.model.view_protection_group_object_params import (
    ViewProtectionGroupObjectParams,
)

v2_client = ClusterClient(
    "10.14.49.155", username="admin", password="Cohe$1ty", domain="LOCAL"
)
objects = list()
for view in v2_client.view.get_views().views:
    objects.append(ViewProtectionGroupObjectParams(id=view.view_id))
view_params = ViewProtectionGroupParams(objects=objects)
body = CreateOrUpdateProtectionGroupRequest(
    storage_domain_id=5,
    policy_id="3174869828959617:1699578611405:2",
    name="Test",
    e`from cohesity_sdk.cluster.cluster_client import ClusterClient
from cohesity_sdk.cluster.model.create_or_update_protection_group_request import (
    CreateOrUpdateProtectionGroupRequest,
)
from cohesity_sdk.cluster.model.view_protection_group_params import (
    ViewProtectionGroupParams,
)
from cohesity_sdk.cluster.model.view_protection_group_object_params import (
    ViewProtectionGroupObjectParams,
)

v2_client = ClusterClient(
    "10.14.49.155", username="admin", password="Cohe$1ty", domain="LOCAL"
)
objects = list()
for view in v2_client.view.get_views().views:
    objects.append(ViewProtectionGroupObjectParams(id=view.view_id))
view_params = ViewProtectionGroupParams(objects=objects)
body = CreateOrUpdateProtectionGroupRequest(
    storage_domain_id=5,
    policy_id="3174869828959617:1699578611405:2",
    name="Test",
    environment="kView",
    view_params=view_params,
)
print(v2_client.protection_group.create_protection_group(body))
```

**Comment by anusajith** [comment]
@naveena-maplelabs , Having issues with V2 client too: https://github.com/cohesity/cohesity_sdk/issues/1. Not sure it didn't have any assignee yet.

**Comment by naveena-maplelabs** [comment]
Issue resolved with V2 SDk 1.2.0 version.

**Comment by anusajith** [comment]
So will there be any fix going in V1 client?

**Comment by naveena-maplelabs** [comment]
@anusajith That need a V1 API fix, our SDK has nothing to do with it. Even with API we can't create job with more than 100+ views.

**Comment by anusajith** [comment]
Thank you @naveena-maplelabs for all your responses.
